### ISSUE TITLE
Master Clean Diaz

### ISSUE THREAD

**Issue by MakeDigitAll** [MakersDigital/CleanDiaz#1]
Enviar documentación y completar colores

**Comment by DavidVillagrana26** [comment]
Se corrigieron los colores de la pagina y se agrego la ubicación de la empresa
Favor de revisar

**Comment by DavidVillagrana26** [comment]
[MASTER CLEAN DIAZ.docx](https://github.com/MakersDigital/CleanDiaz/files/11468187/MASTER.CLEAN.DIAZ.docx)
